### ISSUE TITLE
Is there an example for how to load blob into docarray?

### ISSUE THREAD

**Issue by luquitared** [jina-ai/executor-pdfsegmenter#6]
Hi,

Thank you for building this project! I got the service running in a docker container and it runs without any exceptions.

I am now looking to actually post data to the craft endpoint. I understand the type needed is DocumentArray. I decided to test this locally like so:

``` python
from jina import Flow
import base64

from docarray import DocumentArray, Document
from jina import Flow

with open('1.pdf', 'rb') as blob:
    blobii = base64.b64encode(blob.read())
    doc = DocumentArray(blob=blobii)

f = Flow().add(
    uses='jinahub+docker://PDFSegmenter',
    uses_with={'hostname': 'host.docker.internal'},
)
with f:
    resp = f.post(on='/craft', inputs=doc)
    print(f'{resp[0]}')

#f.to_docker_compose_yaml()
```

Any suggestions on how I can create documents with encoded blobs? I am assuming that this is how I pass files to /craft. Thanks!

**Comment by luquitared** [comment]
Looks like I solved it with this:
``` python
doc = DocumentArray([Document(uri='k.pdf')])
doc[0].load_uri_to_blob()
print(doc[0].blob)
```

but now experiencing a massive error output when attempting to push the document to /craft endpoint. I'm using a mac M1. Here it is:
``` bash
executor0/head@31383[E]:<AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jina/serve/runtimes/head/__init__.py", line 171, in process_data
    response, metadata = await self._handle_data_request(requests, endpoint)
  File "/opt/homebrew/lib/python3.9/site-packages/jina/serve/runtimes/head/__init__.py", line 250, in _handle_data_request
    worker_results = await asyncio.gather(*worker_send_tasks)
  File "/opt/homebrew/lib/python3.9/site-packages/jina/serve/networking.py", line 487, in task_wrapper
    await call_result,
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. (raised from /opt/homebrew/lib/python3.9/site-packages/docker/utils/utils.py:52)
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. (raised from /opt/homebrew/lib/python3.9/site-packages/docker/utils/utils.py:53)
executor0/rep-0@31381[E]:NotFound(HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/0729288f35f0c93084bd96edcf5d242b089965e63d68ab4da19fe59b286bc76d/kill?signal=SIGTERM')) during <bound method BasePod.close of <jina.orchestrate.pods.container.ContainerPod object at 0x14a20b580>>
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 62, in _get_results
    async for resp in stub.Call(
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>"
        debug_error_string = "{"created":"@1649732243.442652000","description":"Error received from peer ipv4:0.0.0.0:49484","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>","grpc_status":2}"
>"
        debug_error_string = "{"created":"@1649732243.445666000","description":"Error received from peer ipv4:0.0.0.0:52713","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>"\n\tdebug_error_string = "{"created":"@1649732243.442652000","description":"Error received from peer ipv4:0.0.0.0:49484","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>","grpc_status":2}"\n>","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lucasnegritto/Desktop/code/vectotron/jina_test.py", line 18, in <module>
    resp = f.post(on='/craft', inputs=doc)
  File "/opt/homebrew/lib/python3.9/site-packages/jina/clients/mixin.py", line 156, in post
    return run_async(
  File "/opt/homebrew/lib/python3.9/site-packages/jina/helper.py", line 1298, in run_async
    return get_or_reuse_loop().run_until_complete(func(*args, **kwargs))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/opt/homebrew/lib/python3.9/site-packages/jina/clients/mixin.py", line 147, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/opt/homebrew/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 128, in _get_results
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 109, in _get_results
    raise BadClient(msg) from rpc_ex
jina.excepts.BadClient: gRPC error: StatusCode.UNKNOWN Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>"
        debug_error_string = "{"created":"@1649732243.442652000","description":"Error received from peer ipv4:0.0.0.0:49484","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/0729288f35f0c93084bd96edcf5d242b089965e63d68ab4da19fe59b286bc76d/kill?signal=SIGTERM

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jina/orchestrate/pods/__init__.py", line 167, in close
    self._terminate()
  File "/opt/homebrew/lib/python3.9/site-packages/jina/orchestrate/pods/container.py", line 394, in _terminate
    self._container.kill(signal='SIGTERM')
  File "/opt/homebrew/lib/python3.9/site-packages/docker/models/containers.py", line 276, in kill
    return self.client.api.kill(self.id, signal=signal)
  File "/opt/homebrew/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/docker/api/container.py", line 796, in kill
    self._raise_for_status(res)
  File "/opt/homebrew/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/homebrew/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/0729288f35f0c93084bd96edcf5d242b089965e63d68ab4da19fe59b286bc76d/kill?signal=SIGTERM: Not Found ("Cannot kill container: 0729288f35f0c93084bd96edcf5d242b089965e63d68ab4da19fe59b286bc76d: No such container: 0729288f35f0c93084bd96edcf5d242b089965e63d68ab4da19fe59b286bc76d")
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. (raised from /opt/homebrew/lib/python3.9/site-packages/docker/utils/utils.py:52)
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. (raised from /opt/homebrew/lib/python3.9/site-packages/docker/utils/utils.py:53)
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. (raised from /opt/homebrew/lib/python3.9/site-packages/docker/utils/utils.py:52)
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. (raised from /opt/homebrew/lib/python3.9/site-packages/docker/utils/utils.py:53)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/jina/clients/base/grpc.py:62 in _get_results           │
│                                                                                                  │
│    59 │   │   │   │   │   total_length=self._inputs_length, disable=not (self.show_progress)     │
│    60 │   │   │   │   ) as p_bar:                                                                │
│    61 │   │   │   │   │                                                                          │
│ ❱  62 │   │   │   │   │   async for resp in stub.Call(                                           │
│    63 │   │   │   │   │   │   req_iter,                                                          │
│    64 │   │   │   │   │   │   compression=GRPC_COMPRESSION_MAP.get(                              │
│    65 │   │   │   │   │   │   │   compression.lower(), grpc.Compression.NoCompression            │
│ /opt/homebrew/lib/python3.9/site-packages/grpc/aio/_call.py:326 in _fetch_stream_responses       │
│                                                                                                  │
│   323 │   │   │   message = await self._read()                                                   │
│   324 │   │                                                                                      │
│   325 │   │   # If the read operation failed, Core should explain why.                           │
│ ❱ 326 │   │   await self._raise_for_status()                                                     │
│   327 │                                                                                          │
│   328 │   def __aiter__(self) -> AsyncIterable[ResponseType]:                                    │
│   329 │   │   self._update_response_style(_APIStyle.ASYNC_GENERATOR)                             │
│                                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/grpc/aio/_call.py:236 in _raise_for_status             │
│                                                                                                  │
│   233 │   │   │   raise asyncio.CancelledError()                                                 │
│   234 │   │   code = await self.code()                                                           │
│   235 │   │   if code != grpc.StatusCode.OK:                                                     │
│ ❱ 236 │   │   │   raise _create_rpc_error(await self.initial_metadata(), await                   │
│   237 │   │   │   │   │   │   │   │   │   self._cython_call.status())                            │
│   238 │                                                                                          │
│   239 │   def _repr(self) -> str:                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_chan
nel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all 
addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>"
        debug_error_string = "{"created":"@1649732243.442652000","description":"Error received from peer 
ipv4:0.0.0.0:49484","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC 
that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = 
"{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"ref
erenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all 
addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>","grpc_status":2}"
>"
        debug_error_string = "{"created":"@1649732243.445666000","description":"Error received from peer 
ipv4:0.0.0.0:52713","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC 
that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated 
with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = 
"{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"ref
erenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all 
addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>"\n\tdebug_error_string = 
"{"created":"@1649732243.442652000","description":"Error received from peer 
ipv4:0.0.0.0:49484","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC 
that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = 
"{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"ref
erenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all 
addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>","grpc_status":2}"\n>","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/lucasnegritto/Desktop/code/vectotron/jina_test.py:18 in <module>                          │
│                                                                                                  │
│   15 │   uses_with={'hostname': 'host.docker.internal'},                                         │
│   16 )                                                                                           │
│   17 with f:                                                                                     │
│ ❱ 18 │   resp = f.post(on='/craft', inputs=doc)                                                  │
│   19 │   print(f'{resp[0].text}')                                                                │
│   20                                                                                             │
│   21 #f.to_docker_compose_yaml()                                                                 │
│ /opt/homebrew/lib/python3.9/site-packages/jina/clients/mixin.py:156 in post                      │
│                                                                                                  │
│   153 │   │   │   if return_results:                                                             │
│   154 │   │   │   │   return result                                                              │
│   155 │   │                                                                                      │
│ ❱ 156 │   │   return run_async(                                                                  │
│   157 │   │   │   _get_results,                                                                  │
│   158 │   │   │   inputs=inputs,                                                                 │
│   159 │   │   │   on_done=on_done,                                                               │
│                                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/jina/helper.py:1298 in run_async                       │
│                                                                                                  │
│   1295 │   │   │   │   'please report this issue here: https://github.com/jina-ai/jina'          │
│   1296 │   │   │   )                                                                             │
│   1297 │   else:                                                                                 │
│ ❱ 1298 │   │   return get_or_reuse_loop().run_until_complete(func(*args, **kwargs))              │
│   1299                                                                                           │
│   1300                                                                                           │
│   1301 def slugify(value):                                                                       │
│                                                                                                  │
│ /Users/lucasnegritto/Desktop/code/vectotron/uvloop/loop.pyx:1501 in                              │
│ uvloop.loop.Loop.run_until_complete                                                              │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/Users/lucasnegritto/Desktop/code/vectotron/uvloop/loop.pyx'                                    │
│                                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/jina/clients/mixin.py:147 in _get_results              │
│                                                                                                  │
│   144 │   │                                                                                      │
│   145 │   │   async def _get_results(*args, **kwargs):                                           │
│   146 │   │   │   result = [] if return_responses else DocumentArray()                           │
│ ❱ 147 │   │   │   async for resp in c._get_results(*args, **kwargs):                             │
│   148 │   │   │   │   if return_results:                                                         │
│   149 │   │   │   │   │   if return_responses:                                                   │
│   150 │   │   │   │   │   │   result.append(resp)                                                │
│                                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/jina/clients/base/grpc.py:128 in _get_results          │
│                                                                                                  │
│   125 │   │   │   │   │   │   │   logger=self.logger,                                            │
│   126 │   │   │   │   │   │   )                                                                  │
│   127 │   │   │   │   else:                                                                      │
│ ❱ 128 │   │   │   │   │   raise e                                                                │
│   129                                                                                            │
│                                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/jina/clients/base/grpc.py:109 in _get_results          │
│                                                                                                  │
│   106 │   │   │   │   │   │   'please double check your input iterator'                          │
│   107 │   │   │   │   │   ) from rpc_ex                                                          │
│   108 │   │   │   │   else:                                                                      │
│ ❱ 109 │   │   │   │   │   raise BadClient(msg) from rpc_ex                                       │
│   110 │   │   │                                                                                  │
│   111 │   │   │   except (                                                                       │
│   112 │   │   │   │   grpc.aio._call.AioRpcError,                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
BadClient: gRPC error: StatusCode.UNKNOWN Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_chan
nel.cc","file_line":3129,"referenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all 
addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>"
        debug_error_string = "{"created":"@1649732243.442652000","description":"Error received from peer 
ipv4:0.0.0.0:49484","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Unexpected <class 'grpc.aio._call.AioRpcError'>: <AioRpcError of RPC 
that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = 
"{"created":"@1649732243.438603000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"ref
erenced_errors":[{"created":"@1649732243.438601000","description":"failed to connect to all 
addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>","grpc_status":2}"
>
```

**Comment by cristianmtr** [comment]
Hey @luquitared 

You need to provide the data in `.tensor` attribute of the `Document`.

```python
...
    blobii = base64.b64encode(blob.read())
    doc = DocumentArray([Document(blob=blobii)])
    doc[0].convert_blob_to_tensor()
```

**Comment by luquitared** [comment]
Ok, that fixed my issue, but now how do I send the data to /craft and get back the text of my PDF? I am using the same code as above but the document only has a .tensor and empty .text attribute

**Comment by cristianmtr** [comment]
It's in the `.chunks` of the document

Check the [usage guide](https://github.com/jina-ai/executor-pdfsegmenter#loading-data) I just added in the README

**Comment by luquitared** [comment]
hmmm I am returned an empty array

perhaps it is something wrong with my .pdf file?

**Comment by luquitared** [comment]
Yes just tested with a different PDF and it works. Might be good to test if a file is compatible before attempting to use /craft. In my case, if i use the incompatible file (unsure why it does not work) it causes the large error posted above up there ^^. Thanks for the support!
